name: 'Build Databricks Deployment Workflow'

on:
  #push:
   # branches: [ "main" ]
  pull_request:
     branches: [ "main" ]
  
permissions:
  contents: read

   
env: 
  TF_VAR_databricks_host: ${{ secrets.DB_DEV_HOST }}
  TF_VAR_databricks_token: ${{ secrets.DB_DEV_PAT }}

jobs:  
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform
        

    

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v1
      with :
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Init Terraform
      run: |                      
        unset TF_WORKSPACE
        # export TF_WORKSPACE="mk-test-api-ws-api-staging"
        export TF_WORKSPACE= ${{secrets.TF_WORKSPACE}}
        
        terraform init   
            
    - name: Plan Terraform
      id: plan     
      run: | 
        unset  TF_WORKSPACE             
        export TF_WORKSPACE="mk-test-api-ws-api-staging"    
        
        terraform plan             
               
    - name: Apply Terraform
      id: apply      
      run: |
        # export TF_WORKSPACE="dev"
        unset  TF_WORKSPACE             
        export TF_WORKSPACE="mk-test-api-ws-api-staging"    
        terraform apply -auto-approve 
      
          
      




       




    
         
      
      
      
      
