name: 'Build Databricks Deployment Workflow'

on:
  #push:
   # branches: [ "main" ]
  pull_request:
     branches: [ "main" ]
  
permissions:
  contents: read

env:
    DATABRICKS_HOST: ${{secrets.DB_DEV_HOST}}
    DATABRICKS_TOKEN: ${{secrets.DB_DEV_PAT}} 

jobs:  
  build-and-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    #environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform
     
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: Prepare Terraform
      uses: hashicorp/setup-terraform@v1
      with :
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Init Terraform
      run: terraform init
    
    - name: Plan Terraform
      run: terraform plan


       




    
         
      
      
      
      
