name: 'Deploy Databrick Workflow'

on:
  push:
    branches: [ "main" ]  

permissions:
  contents: read

env: 
    TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST }}
    TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
    TF_WORKSPACE: ${{vars.TF_WORKSPACE}} #"mk-test-api-ws-api" 

jobs:  
  terraform:
    name: 'Deploy Databricks Notebooks and Jobs'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
     
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Download build files
      run: echo "download artifacts TODO"
      #uses: actions/download-artifact@v3
      #with:
      #  name: tf-files

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Init Terraform
      run: |                                       
        terraform init   

    - name: Plan Terraform
      id: plan     
      run: | 
        terraform plan             
               
    - name: Apply Terraform
      id: apply      
      run: |        
        terraform apply -auto-approve    
      
      
      
